---
- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  changed_when: false
  notify: Trigger udev

- name: Trigger udev
  ansible.builtin.command: udevadm trigger
  become: true
  changed_when: false
