---
- name: Deploy ros2-master on server
  hosts: server
  become: true
  pre_tasks:
    - name: Sync repository
      ansible.builtin.include_tasks: ../../tasks/repo_sync.yml
  tasks:
    - name: Deploy ros2-master
      ansible.builtin.include_tasks: ../../tasks/resolve_and_deploy.yml
      vars:
        _deploy_node_name: ros2-master
