---
- name: Deploy robot_localization_ekf on client
  hosts: client
  become: true
  pre_tasks:
    - name: Sync repository
      ansible.builtin.include_tasks: ../../tasks/repo_sync.yml
  tasks:
    - name: Deploy robot_localization_ekf
      ansible.builtin.include_tasks: ../../tasks/resolve_and_deploy.yml
      vars:
        _deploy_node_name: robot_localization_ekf
