---
- name: Deploy web_ui on client
  hosts: client
  become: true
  pre_tasks:
    - name: Sync repository
      ansible.builtin.include_tasks: ../../tasks/repo_sync.yml
  tasks:
    - name: Deploy web_ui
      ansible.builtin.include_tasks: ../../tasks/resolve_and_deploy.yml
      vars:
        _deploy_node_name: web_ui
