"""Planner speed and result stability with the deployed client.yml config (the RPi 5 is several times slower than a
Mac, so plan time on the Mac is budgeted well below the web UI /api/grasp 30 s timeout).

Set GRASP_SPEED_SKIP=1 to skip the timing tests on slow CI; the golden-plan test always runs.
tests/data/grasp_golden.json holds plans generated by the planner before the speed work (feasible scenarios of the
sim matrix: waypoint joints and straight-line samples); they must stay within GOLDEN_TOL_RAD.
"""

import importlib.util
import json
import os
import time
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

from mcp_server.floor_guard import FloorGuard, JawModel, SurfaceModel
from mcp_server.grasp import GraspPlan, GraspPlanner, ObjectSpec, grasp_params
from mcp_server.ik import ArmKinematics

SCRIPT = Path(__file__).resolve().parents[3] / "sim" / "grasp_sim" / "scripts" / "plan_matrix.py"
GOLDEN = Path(__file__).parent / "data" / "grasp_golden.json"
GOLDEN_TOL_RAD = 1e-6
AUTO_BUDGET_S = 1.0
ANGLED_BUDGET_S = 1.0
UNREACHABLE_BUDGET_S = 0.2
SKIP_TIMING = os.environ.get("GRASP_SPEED_SKIP") == "1"
SEED = {"shoulder_pan": 0.0, "shoulder_lift": 0.0, "elbow_flex": 1.2, "wrist_flex": 0.3, "wrist_roll": 0.0}
timing = pytest.mark.skipif(SKIP_TIMING, reason="GRASP_SPEED_SKIP=1")


def load_script() -> ModuleType:
    spec = importlib.util.spec_from_file_location("plan_matrix", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


MATRIX = load_script()
CFG = MATRIX.client_config()
KIN = ArmKinematics(
    CFG.arm.urdf_path,
    margin=CFG.limits.arm_limit_margin_rad,
    joint_offsets=CFG.arm.joint_offsets_rad.model_dump(),
    tool_offset=tuple(CFG.arm.tool_offset_m.model_dump().values()),
    limit_overrides=CFG.arm.joint_limit_overrides_rad,
)
MOUNT = CFG.arm.base_in_base_link
assert MOUNT is not None
JAW = JawModel(KIN, CFG.arm.jaw_open_axis, CFG.arm.gripper_closed_rad)
PLANNER = GraspPlanner(KIN, CFG, FloorGuard(KIN, CFG.floor_guard, MOUNT, JAW), JAW)
PARAMS = grasp_params(CFG.grasp, None)
FLOOR = -CFG.arm.arm_base_height_m
REFERENCE = {"x": 0.25, "y": 0.0, "bottom": FLOOR, "size": (0.04, 0.04, 0.04), "gap": 0.0}


def run(
    x: float,
    y: float,
    bottom: float,
    size: tuple[float, float, float],
    gap: float,
    strategy: str,
    pitch: float | None,
    surface_z: float | None = None,
) -> GraspPlan:
    surface = SurfaceModel(
        surface_z_m=(bottom - gap if surface_z is None else surface_z) + MOUNT.z,
        tilt=None,
        tilt_source="none",
        mount=MOUNT,
    )
    obj = MATRIX.object_spec(x, y, bottom, size, gap)
    assert isinstance(obj, ObjectSpec)
    return PLANNER.plan(obj, strategy, PARAMS, surface, dict(SEED), pitch)


def timed(strategy: str, pitch: float | None = None, **override: Any) -> tuple[float, GraspPlan]:
    KIN.solutions.clear()  # cold: no IK solved by an earlier test
    start = time.perf_counter()
    plan = run(**(REFERENCE | override), strategy=strategy, pitch=pitch)
    return time.perf_counter() - start, plan


def close(a: dict[str, float], b: dict[str, float]) -> bool:
    return a.keys() == b.keys() and all(abs(a[k] - b[k]) <= GOLDEN_TOL_RAD for k in a)


@pytest.mark.parametrize("case", json.loads(GOLDEN.read_text()), ids=lambda c: c["key"])
def test_feasible_plans_match_the_golden_plans(case: dict[str, Any]) -> None:
    plan = run(
        case["x"],
        case["y"],
        case["support_z"],
        tuple(case["size"]),
        case["gap"],
        case["strategy"],
        case["pitch"],
        surface_z=case["surface_z"],
    )
    assert plan.feasible, plan.reasons
    assert plan.strategy == case["chosen"]
    assert plan.approach_pitch_rad == pytest.approx(case["pitch_rad"], abs=GOLDEN_TOL_RAD)
    assert plan.wrist_roll_rad == pytest.approx(case["roll"], abs=GOLDEN_TOL_RAD)
    assert [w.label for w in plan.waypoints] == [w["label"] for w in case["waypoints"]]
    assert all(close(w.joints, g["joints"]) for w, g in zip(plan.waypoints, case["waypoints"], strict=True))
    assert plan.segments.keys() == case["segments"].keys()
    for label, samples in case["segments"].items():
        assert len(plan.segments[label]) == len(samples)
        assert all(close(a, b) for a, b in zip(plan.segments[label], samples, strict=True)), label


@timing
def test_auto_on_the_reference_scenario_is_under_a_second() -> None:
    elapsed, plan = timed("auto")
    assert plan.feasible
    assert elapsed < AUTO_BUDGET_S, f"auto took {elapsed:.2f} s"


@timing
def test_infeasible_angled_plan_fails_fast() -> None:
    elapsed, plan = timed("angled", 45.0)
    assert not plan.feasible and plan.reasons
    assert elapsed < ANGLED_BUDGET_S, f"angled took {elapsed:.2f} s"


@timing
def test_auto_on_an_infeasible_object_fails_fast_with_reasons() -> None:
    elapsed, plan = timed("auto", x=0.30, bottom=-0.25)
    assert not plan.feasible and plan.reasons
    assert elapsed < AUTO_BUDGET_S, f"auto took {elapsed:.2f} s"


@timing
def test_unreachable_object_is_rejected_without_an_ik_search() -> None:
    elapsed, plan = timed("auto", x=0.80)
    assert not plan.feasible and plan.reasons
    assert elapsed < UNREACHABLE_BUDGET_S, f"unreachable took {elapsed:.2f} s"
